### ISSUE TITLE
Add note as shortcut in the left sidebar

### ISSUE THREAD

**Issue by gxingh** [Automattic/Simplenote-United#114]
### What
Ability to pin certain notes in the left sidebar. Just like tags are present in the left but for quick access.

### Why
For quick access to notes which we visit multiple times daily or which are more important than others. Like a todo note or an index note with links to internal notes.

### How
Maybe a shortcuts part on top of tags? Maybe have limited number of shortcuts allowed?

*I love the app and am very thankful to the community.*

**Comment by dmsnell** [comment]
Hi @iamtherealgd 👋 

Look for the "Pin to top" option on a note. This doesn't pin it to the sidebar but it should pin the note to the top of the notes list regardless of sort options. I'm going to close this issue because I believe we already support what you are asking, but we can reopen it if I misunderstood you.

On macOS you can right-click on a note to pin it, on the web/Windows/Linux you can hover over the note in the note list and see a pin icon appear and then click on that, and on Android and iOS check in the options for the individual note.

**Comment by gxingh** [comment]
No thats not what I meant.

I know theres a "Pin to Top" feature and I use it. What I was trying to say is to make the note appear on the left hand menu itself where tags appear. Like a "shortcut"? Case in point if I have multiple notes pinned or if I want a note to stand out further from other notes maybe?

I understand this issue/feature won't resonate with everyone but thats okay, its not like its a dealbreaker for anyone.

**Comment by dmsnell** [comment]
no worries, I'll add it to our internal feature tracker. we don't have any near-term plans to add something like this, but we will consider it in the longer-term roadmap. thanks for clarifying!

**Comment by dmsnell** [comment]
to be clear, you are saying you want a second tier of pinning? as in, maybe you have twenty notes pinned but you want one of them to be _super-pinned_ but you also don't want to grab that list of notes into a kind of pinning tag?

the tag list is actually manually sortable so if you have a tag named "NoteShortcuts" and tag all those notes with it, then move that tag to the top of the tag list, would that be different than what you are asking for?

**Comment by gxingh** [comment]
That could be the solution, yes.
I was thinking instead of only tags, we could put notes for direct access but what you mentioned pretty much almost solves my issue.
Thanks!
