### ISSUE TITLE
End-to-end encryption (E2EE) for notes

### ISSUE THREAD

**Issue by articlecat** [Automattic/Simplenote-United#53]
### What
It would be great to see end-to-end encryption (E2EE) for notes. The client (Electron, Android, iOS, macOS, and web) should encrypt notes before syncing them with the server, and the notes should be stored on the server in an encrypted form. The server should not be able to decrypt the notes, and only the client should be able to decrypt the notes with the user's password.

### Why
End-to-end encryption ensures that the notes are secure from eavesdropping. Users would be able to trust Simplenote with more sensitive information if they know their data is end-to-end encrypted (especially through open source software).

### How
Other note-taking apps including [Standard Notes](https://github.com/standardnotes), [Joplin](https://github.com/laurent22/joplin), and [Turtl](https://github.com/turtl) already implement end-to-end encryption. Their methods may be useful.

**Comment by trymeouteh** [comment]
This is essential to ensure privacy. I like this app but I cannot trust Simplenote until this is implimented.

**Comment by Tav0** [comment]
Any updates on this?

**Comment by codebykat** [comment]
Hi @Tav0 et. al., this is something we hope to implement someday, but is extremely technically complex and would require essentially the entire application to be rewritten (backend and all clients). This is because right now the backend syncs changes between multiple clients, which obviously it would be unable to do if the data was encrypted. So change reconciliation would have to be implemented by the clients instead.

As fast, reliable cross-device syncing is one of our most core features, it's something we need to be very cautious about changing.

It's worth noting that all Simplenote data is already encrypted "in flight", which is something we feel is important, because it guards against the most common way unencrypted data gets compromised. Also, we store everything on our own servers rather than outsourcing to a third party. More here: https://simplenote.com/help/#encryption

All of that being said, we do have some ideas for how we might be able to tackle this idea, and we take feedback into account when planning future work, so I appreciate everyone's thoughts here. We'll hopefully have something more to share about this down the road.

I'm going to close this issue for now because we generally use GitHub for tracking bugs, active work, and feature parity rather than requests for future enhancements; I don't want folks to mistakenly follow this issue for updates. Any news on major features like this will be posted on our blog: https://simplenote.com/blog/

**Comment by justauserid** [comment]
> rather than requests for future enhancements

Where do we go for this, then?

**Comment by jenabaivab** [comment]
Is this planned to be integrated? Really looking forward to some updates @codebykat

**Comment by codebykat** [comment]
@justauserid If we've replied to an issue here, then we're tracking it. We have an internal tracker since Simplenote code is spread over multiple repositories (plus we get requests via email, Twitter, etc.). New features will be announced on the blog: https://simplenote.com/blog/

@jenabaivab No updates to share unfortunately. It is on our roadmap but we have been kept busy with other projects.
